# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
