# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0002_auto_20171206_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_body',
            field=models.TextField(),
        ),
    ]
