# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0003_auto_20171207_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL),
        ),
    ]
